:technologist: Making local tests/builds easier
Signed-off-by: Muhammed Hussein Karimi <info@karimi.dev>

diff --git a/.ci/common b/.ci/common
--- a/.ci/common
+++ b/.ci/common
@@ -15,13 +15,15 @@ export CI_REGISTRY="localhost:5000"
 export CI_TAG="${COMMIT}-ci"
 export CI_IMAGE_REPO="${IMAGE}"
 export CI_IMAGE_URI="${CI_REGISTRY}/${CI_IMAGE_REPO}:${CI_TAG}"
-export CI_IMAGE_PLATFORMS=linux/amd64
-export CI_TEST="${CI_TEST:-false}"
+## See `docker system info --format '{{.ClientInfo.Os}}/{{.ClientInfo.Arch}}'` for default platform
+export CI_IMAGE_PLATFORMS="local"
+export CI_TEST="${CI_TEST:-true}"
 if [[ "${CI_TEST}" == "false" ]]; then
-  export CI_IMAGE_PLATFORMS="${CI_IMAGE_PLATFORMS},linux/arm64"
+  export CI_IMAGE_PLATFORMS="linux/amd64,linux/arm64"
 fi
 
-command -v docker &>/dev/null || ( echo 'docker not found. exiting...'; exit 1 )
+command -v docker &>/dev/null || ( echo 'Docker is not installed. Aborting.'; exit 1 )
+docker buildx version &>/dev/null || ( echo 'Docker Buildx plugin is not installed. Aborting.'; exit 1 )
 
 function TagAndPushImage() {
   REPO="$1"
